### ISSUE TITLE
issues and fixes(?)

### ISSUE THREAD

**Issue by PapiOphidian** [KenRouKoro/C3H6N6O6#23]
I was doing some local edits to the mod to see if I could get it to work and I did!

Changes I made which work are as follows:

c3h6n6o6.accesswidener
```
- accessible  field net/minecraft/server/world/ThreadedAnvilChunkStorage structureManager Lnet/minecraft/structure/StructureManager;
+ accessible  field net/minecraft/server/world/ThreadedAnvilChunkStorage structureTemplateManager Lnet/minecraft/structure/StructureTemplateManager;
```

mixin/c2me/CheckedThreadLocalRandomMixin.java
```
- if (owner != null && (CalculationController.getServer().isOnThread() ? owner : Thread.currentThread()) != owner)
+ if (owner != null && (CalculationController.getServer() != null && CalculationController.getServer().isOnThread() ? owner : Thread.currentThread()) != owner)
```

I also re-targeted
c2me fixes worldgen threading issues to com.ishland.c2me:c2me-fixes-worldgen-threading-issues:0.2.0+alpha.9.9

Some issues during playing with these changes still pop up particularly with the hopper minecart which (as far as I can tell, I'm no java expert) is because lithium still applies an entity mixin for hopper minecart even when the entity mixin is disabled in the lithium config:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
        at me.jellysquid.mods.lithium.common.entity.movement_tracker.SectionedEntityMovementTracker.emitEntityMovement(SectionedEntityMovementTracker.java:183) ~[lithium-fabric-mc1.19.2-0.11.1.jar:?]
        at net.minecraft.world.entity.EntityTrackingSection.trackEntityMovement(EntityTrackingSection.java:2065) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerEntityManager$Listener.notifyMovementListeners(ServerEntityManager.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerEntityManager$Listener.handler$bnh000$lithium$updateEntityTrackerEngine(ServerEntityManager.java:540) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerEntityManager$Listener.updateEntityPosition(ServerEntityManager.java:71) ~[server-intermediary.jar:?]
        at dev.architectury.hooks.level.entity.fabric.EntityHooksImpl$1.updateEntityPosition(EntityHooksImpl.java:36) ~[architectury-6.5.77-fabric.jar:?]
        at net.minecraft.entity.Entity.setPos(Entity.java:3295) ~[server-intermediary.jar:?]
        at net.minecraft.entity.Entity.setPosition(Entity.java:438) ~[server-intermediary.jar:?]
        at net.minecraft.entity.vehicle.AbstractMinecartEntity.moveOnRail(AbstractMinecartEntity.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.entity.vehicle.AbstractMinecartEntity.tick(AbstractMinecartEntity.java:348) ~[server-intermediary.jar:?]
        at net.minecraft.entity.vehicle.HopperMinecartEntity.tick(HopperMinecartEntity.java:91) ~[server-intermediary.jar:?]
        at cn.korostudio.c3h6n6o6.thread.CalculationController.lambda$callEntityTick$2(CalculationController.java:133) ~[C3H6N6O6-1.0.0-beta11-1.19.2.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

If updates could be done fixing the issues, I'd greatly appreciate it.

I also accidentally tested the mod without the lithium mixins disabled thinking they were already and got another error about class cn.korostudio.c3h6n6o6.fastutil.Int2ObjectConcurrentHashMap cannot be cast to class it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap

I ended up changing the implementation from an implements to an extends of it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap<V> and fixing the errors that the current overrides had and that didn't crash much to my surprise, although some new errors did pop up, but they weren't fatal and didn't affect my limited play testing:
```
黑索金异常捕捉:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
	at me.jellysquid.mods.lithium.common.entity.movement_tracker.SectionedEntityMovementTracker.emitEntityMovement(SectionedEntityMovementTracker.java:183) ~[lithium-fabric-mc1.19.2-0.11.1.jar:?]
	at net.minecraft.world.entity.EntityTrackingSection.trackEntityMovement(EntityTrackingSection.java:2565) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerEntityManager$Listener.notifyMovementListeners(ServerEntityManager.java:568) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerEntityManager$Listener.handler$bpp000$lithium$updateEntityTrackerEngine(ServerEntityManager.java:540) ~[server-intermediary.jar:?]
	at net.minecraft.server.world.ServerEntityManager$Listener.updateEntityPosition(ServerEntityManager.java:71) ~[server-intermediary.jar:?]
	at dev.architectury.hooks.level.entity.fabric.EntityHooksImpl$1.updateEntityPosition(EntityHooksImpl.java:36) ~[architectury-6.5.77-fabric.jar:?]
	at net.minecraft.entity.Entity.setPos(Entity.java:3295) ~[server-intermediary.jar:?]
	at net.minecraft.entity.Entity.setPosition(Entity.java:438) ~[server-intermediary.jar:?]
	at net.minecraft.entity.vehicle.AbstractMinecartEntity.moveOnRail(AbstractMinecartEntity.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.entity.vehicle.AbstractMinecartEntity.tick(AbstractMinecartEntity.java:348) ~[server-intermediary.jar:?]
	at net.minecraft.entity.vehicle.HopperMinecartEntity.tick(HopperMinecartEntity.java:91) ~[server-intermediary.jar:?]
	at cn.korostudio.c3h6n6o6.thread.CalculationController.lambda$callEntityTick$2(CalculationController.java:133) ~[C3H6N6O6-1.0.0-beta11-1.19.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
	
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 33
	at it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap.rehash(Reference2IntOpenHashMap.java:1387) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap.insert(Reference2IntOpenHashMap.java:277) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap.put(Reference2IntOpenHashMap.java:285) ~[fastutil-8.5.6.jar:?]
	at me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette.addEntry(LithiumHashPalette.java:106) ~[lithium-fabric-mc1.19.2-0.11.1.jar:?]
	at me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette.computeEntry(LithiumHashPalette.java:86) ~[lithium-fabric-mc1.19.2-0.11.1.jar:?]
	at me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette.index(LithiumHashPalette.java:68) ~[lithium-fabric-mc1.19.2-0.11.1.jar:?]
	at net.minecraft.world.chunk.PalettedContainer.swap(PalettedContainer.java:129) ~[server-intermediary.jar:?]
	at net.minecraft.world.chunk.PalettedContainer.swap(PalettedContainer.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.world.chunk.ChunkSection.setBlockState(ChunkSection.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.world.chunk.ChunkSection.setBlockState(ChunkSection.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.world.chunk.WorldChunk.setBlockState(WorldChunk.java:234) ~[server-intermediary.jar:?]
	at net.minecraft.world.World.setBlockState(World.java:221) ~[server-intermediary.jar:?]
	at net.minecraft.world.World.setBlockState(World.java:206) ~[server-intermediary.jar:?]
	at net.minecraft.entity.FallingBlockEntity.tick(FallingBlockEntity.java:172) ~[server-intermediary.jar:?]
	at cn.korostudio.c3h6n6o6.thread.CalculationController.lambda$callEntityTick$2(CalculationController.java:133) ~[C3H6N6O6-1.0.0-beta11-1.19.2.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

Like I said, I'm no expert in java because I'm literally just a beginner, but idk if these errors happened on your end while making the mod or something similar, but if support for the entities and collections mixins could be added that would be awesome. Of course, not necessary because I understand limitations

**Comment by PapiOphidian** [comment]
A lot more still needs to be done. I've been trying stuff out locally, but my work usually ends up crashing by watchdog from endTick

**Comment by PapiOphidian** [comment]
I'll close this issue and open a draft PR soon so you can also look at it and either help or tell me what's good and bad
